all:config

server:
	@echo "running the server..."
	@cd thomas_the_tank_engine_app
	@bin/rails server

config:
	@echo "installing dependancies..."
	@sudo apt install ruby rails
	@bundle install
	@yarn install