all:run

run:
	@echo "executing fill.py..."
	@python3 fill.py

config:
	@echo "installing dependancies..."
	@pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118
	@pip install -r requirements.txt